// <auto-generated />
using System;
using AprovadosConcursosApi.Infrastructure.Data.ContextBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AprovadosConcursosApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260627005528_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AprovadosConcursosApi.Domain.Entities.Assunto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DisciplinaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DisciplinaId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DisciplinaId");

                    b.HasIndex("DisciplinaId1");

                    b.ToTable("Assuntos");
                });

            modelBuilder.Entity("AprovadosConcursosApi.Domain.Entities.Banca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sigla")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Site")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bancas");
                });

            modelBuilder.Entity("AprovadosConcursosApi.Domain.Entities.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("AprovadosConcursosApi.Domain.Entities.Disciplina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Disciplinas");
                });

            modelBuilder.Entity("AprovadosConcursosApi.Domain.Entities.Edital", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid>("BancaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CargoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CargoId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInscricaoFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInscricaoInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataProva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinkEdital")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroEdital")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrgaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrgaoId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantidadeVagas")
                        .HasColumnType("int");

                    b.Property<decimal>("Salario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BancaId");

                    b.HasIndex("CargoId");

                    b.HasIndex("CargoId1");

                    b.HasIndex("OrgaoId");

                    b.HasIndex("OrgaoId1");

                    b.ToTable("Editais");
                });

            modelBuilder.Entity("AprovadosConcursosApi.Domain.Entities.Orgao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Site")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orgaos");
                });

            modelBuilder.Entity("AprovadosConcursosApi.Domain.Entities.Questao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlternativaA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlternativaB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlternativaC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlternativaD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlternativaE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<Guid>("AssuntoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssuntoId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid>("BancaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DisciplinaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DisciplinaId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gabarito")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssuntoId");

                    b.HasIndex("AssuntoId1");

                    b.HasIndex("BancaId");

                    b.HasIndex("DisciplinaId");

                    b.HasIndex("DisciplinaId1");

                    b.ToTable("Questoes");
                });

            modelBuilder.Entity("AprovadosConcursosApi.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AprovadosConcursosApi.Domain.Entities.Assunto", b =>
                {
                    b.HasOne("AprovadosConcursosApi.Domain.Entities.Disciplina", "Disciplina")
                        .WithMany()
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AprovadosConcursosApi.Domain.Entities.Disciplina", null)
                        .WithMany("Assuntos")
                        .HasForeignKey("DisciplinaId1");

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("AprovadosConcursosApi.Domain.Entities.Edital", b =>
                {
                    b.HasOne("AprovadosConcursosApi.Domain.Entities.Banca", "Banca")
                        .WithMany("Editais")
                        .HasForeignKey("BancaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AprovadosConcursosApi.Domain.Entities.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AprovadosConcursosApi.Domain.Entities.Cargo", null)
                        .WithMany("Editais")
                        .HasForeignKey("CargoId1");

                    b.HasOne("AprovadosConcursosApi.Domain.Entities.Orgao", "Orgao")
                        .WithMany()
                        .HasForeignKey("OrgaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AprovadosConcursosApi.Domain.Entities.Orgao", null)
                        .WithMany("Editais")
                        .HasForeignKey("OrgaoId1");

                    b.Navigation("Banca");

                    b.Navigation("Cargo");

                    b.Navigation("Orgao");
                });

            modelBuilder.Entity("AprovadosConcursosApi.Domain.Entities.Questao", b =>
                {
                    b.HasOne("AprovadosConcursosApi.Domain.Entities.Assunto", "Assunto")
                        .WithMany()
                        .HasForeignKey("AssuntoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AprovadosConcursosApi.Domain.Entities.Assunto", null)
                        .WithMany("Questoes")
                        .HasForeignKey("AssuntoId1");

                    b.HasOne("AprovadosConcursosApi.Domain.Entities.Banca", "Banca")
                        .WithMany("Questoes")
                        .HasForeignKey("BancaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AprovadosConcursosApi.Domain.Entities.Disciplina", "Disciplina")
                        .WithMany()
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AprovadosConcursosApi.Domain.Entities.Disciplina", null)
                        .WithMany("Questoes")
                        .HasForeignKey("DisciplinaId1");

                    b.Navigation("Assunto");

                    b.Navigation("Banca");

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("AprovadosConcursosApi.Domain.Entities.Assunto", b =>
                {
                    b.Navigation("Questoes");
                });

            modelBuilder.Entity("AprovadosConcursosApi.Domain.Entities.Banca", b =>
                {
                    b.Navigation("Editais");

                    b.Navigation("Questoes");
                });

            modelBuilder.Entity("AprovadosConcursosApi.Domain.Entities.Cargo", b =>
                {
                    b.Navigation("Editais");
                });

            modelBuilder.Entity("AprovadosConcursosApi.Domain.Entities.Disciplina", b =>
                {
                    b.Navigation("Assuntos");

                    b.Navigation("Questoes");
                });

            modelBuilder.Entity("AprovadosConcursosApi.Domain.Entities.Orgao", b =>
                {
                    b.Navigation("Editais");
                });
#pragma warning restore 612, 618
        }
    }
}
